INSERT INTO `DRONE` (SERIAL_NUMBER, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('DRONE_001', 'LIGHTWEIGHT', 100, 100, 'LOADED');
INSERT INTO `DRONE` (SERIAL_NUMBER, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('DRONE_002', 'HEAVYWEIGHT', 500, 54, 'DELIVERING');
INSERT INTO `DRONE` (SERIAL_NUMBER, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('DRONE_003', 'CRUISERWEIGHT', 400, 98, 'DELIVERING');
INSERT INTO `DRONE` (SERIAL_NUMBER, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('DRONE_004', 'MIDDLEWEIGHT', 250, 75, 'DELIVERED');
INSERT INTO `DRONE` (SERIAL_NUMBER, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('DRONE_005', 'LIGHTWEIGHT', 100, 66, 'LOADING');
INSERT INTO `DRONE` (SERIAL_NUMBER, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('DRONE_006', 'CRUISERWEIGHT', 400, 24, 'RETURNING');
INSERT INTO `DRONE` (SERIAL_NUMBER, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('DRONE_007', 'MIDDLEWEIGHT', 250, 38, 'IDLE');
INSERT INTO `DRONE` (SERIAL_NUMBER, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('DRONE_008', 'LIGHTWEIGHT', 100, 18, 'IDLE');
INSERT INTO `DRONE` (SERIAL_NUMBER, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('DRONE_009', 'CRUISERWEIGHT', 400, 44, 'RETURNING');
INSERT INTO `DRONE` (SERIAL_NUMBER, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('DRONE_010', 'MIDDLEWEIGHT', 250, 5, 'IDLE');

INSERT INTO `MEDICATION` (NAME, WEIGHT, CODE, IMAGE) VALUES ('Cefixime-250', 250, 'CEFIXIME_250', 'image-1.png');
INSERT INTO `MEDICATION` (NAME, WEIGHT, CODE, IMAGE) VALUES ('Aspirine-200', 200, 'ASPIRINE_200', 'image-2.png');
INSERT INTO `MEDICATION` (NAME, WEIGHT, CODE, IMAGE) VALUES ('Cefalexine-300', 300, 'CEFALEXINE_300', 'image-3.png');
INSERT INTO `MEDICATION` (NAME, WEIGHT, CODE, IMAGE) VALUES ('Tylenol', 100, 'TYLENOL', 'image-4.png');
INSERT INTO `MEDICATION` (NAME, WEIGHT, CODE, IMAGE) VALUES ('Valium-50', 50, 'VALIUM_200', 'image-5.png');
INSERT INTO `MEDICATION` (NAME, WEIGHT, CODE, IMAGE) VALUES ('Peniciline-400', 400, 'PENICILINE_300', 'image-6.png');
INSERT INTO `MEDICATION` (NAME, WEIGHT, CODE, IMAGE) VALUES ('C-Vitamine', 180, 'C_VITAMINE', 'image-7.png');
INSERT INTO `MEDICATION` (NAME, WEIGHT, CODE, IMAGE) VALUES ('Triple-Antibiotic', 450, 'TRIPLE_ANTIBIOTIC', 'image-8.png');
INSERT INTO `MEDICATION` (NAME, WEIGHT, CODE, IMAGE) VALUES ('Saline-Nasal-Spray', 100, 'SALINE_NASAL_SPRAY', 'image-9.png');
INSERT INTO `MEDICATION` (NAME, WEIGHT, CODE, IMAGE) VALUES ('Cefixime-200', 200, 'CEFIXIME_200', 'image-10.png');
INSERT INTO `MEDICATION` (NAME, WEIGHT, CODE, IMAGE) VALUES ('Cefalexine-200', 200, 'CEFALEXINE_200', 'image-11.png');
INSERT INTO `MEDICATION` (NAME, WEIGHT, CODE, IMAGE) VALUES ('Aspirine-300', 300, 'ASPIRINE_300', 'image-12.png');

INSERT INTO `DRONE_MEDICATIONS` (DRONE_ID, MEDICATIONS_ID) VALUES (1, 9);

INSERT INTO `DRONE_MEDICATIONS` (DRONE_ID, MEDICATIONS_ID) VALUES (2, 1);
INSERT INTO `DRONE_MEDICATIONS` (DRONE_ID, MEDICATIONS_ID) VALUES (2, 4);
INSERT INTO `DRONE_MEDICATIONS` (DRONE_ID, MEDICATIONS_ID) VALUES (2, 5);
INSERT INTO `DRONE_MEDICATIONS` (DRONE_ID, MEDICATIONS_ID) VALUES (2, 9);

INSERT INTO `DRONE_MEDICATIONS` (DRONE_ID, MEDICATIONS_ID) VALUES (3, 3);